<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EgresadosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            
            [
                'NoControl'=>'16270844',
                'name'=>'Wanersert Jonathan',
                'a_paterno'=>'Vazquez',
                'a_materno'=>'Garcia',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto 2',
                'email'=>'L16270844@tuxtla.tecnm.mx',
                'email_verified_at'=>null,
                'telefono'=>'9611985948',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],  
            [
                'NoControl'=>'16270796',
                'name'=>'Hector Alfonso',
                'a_paterno'=>'Martinez',
                'a_materno'=>'Vazquez',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto 2',
                'email'=>'hectormartinez2v@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9671475452',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],   
            [
                'NoControl'=>'16270770',
                'name'=>'Karen Gretchen',
                'a_paterno'=>'Galvez',
                'a_materno'=>'Laguna',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto 3',
                'email'=>'gretchengalvezlaguna@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9614553797',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],  
            [
                'NoControl'=>'17270172',
                'name'=>'Victor Daniel',
                'a_paterno'=>'Solano',
                'a_materno'=>'Hernandez',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto 4',
                'email'=>'victor_1996_darojo@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9612284856',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],  
            [
                'NoControl'=>'16270745',
                'name'=>'Jose Manuel',
                'a_paterno'=>'Castellanos',
                'a_materno'=>'Marroquin',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto 5',
                'email'=>'josecastmarroquin@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9612086374',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],   
            [
                'NoControl'=>'17270832',
                'name'=>'Daniel de Jesus',
                'a_paterno'=>'Angel',
                'a_materno'=>'Montes',
                'carrera'=>'Electrica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto 6',
                'email'=>'danielmontes652@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611175328',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],  
            [
                'NoControl'=>'14270782',
                'name'=>'Einer Alejandro',
                'a_paterno'=>'Lara',
                'a_materno'=>'Aguilar',
                'carrera'=>'Mecanica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto 7',
                'email'=>'L14270782@tuxtla.tecnm.mx',
                'email_verified_at'=>null,
                'telefono'=>'9613138152',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],  
            [
                'NoControl'=>'17271050',
                'name'=>'Jeziel Adonai',
                'a_paterno'=>'Penagos',
                'a_materno'=>'Suarez',
                'carrera'=>'Mecanica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto 8',
                'email'=>'L17271050@tuxtla.tecnm.mx',
                'email_verified_at'=>null,
                'telefono'=>'9613649868',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ], 
            [
                'NoControl'=>'16270786',
                'name'=>'Eugenia Abelina',
                'a_paterno'=>'Jimenez',
                'a_materno'=>'Aguilar',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto 9',
                'email'=>'eugeniaabelinaj@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611010278',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],  
            [
                'NoControl'=>'16270831',
                'name'=>'Citlali Anahi',
                'a_paterno'=>'Toala',
                'a_materno'=>'De la Rosa',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto 10',
                'email'=>'anahi13t@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9671060982',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],        
            [
                'NoControl'=>'16270804',
                'name'=>'Keyla Esmeralda',
                'a_paterno'=>'Montejo',
                'a_materno'=>'Vázquez',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 11',
                'email'=>'esmeraldaxdd@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9613201756',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],          
            
            [
                'NoControl'=>'82270376',
                'name'=>'Juan Gerardo',
                'a_paterno'=>'Rincon',
                'a_materno'=>'Robles',
                'carrera'=>'Electrica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 12',
                'email'=>'rinconchong@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611355406',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],    
            [
                'NoControl'=>'19270668',
                'name'=>'Bryan Eduardo',
                'a_paterno'=>'García',
                'a_materno'=>'López',
                'carrera'=>'Electronica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 13',
                'email'=>'nairbi17.com@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9612726388',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ], 
            [
                'NoControl'=>'20270112',
                'name'=>'Nicolás',
                'a_paterno'=>'Sepúlveda',
                'a_materno'=>'Domínguez',
                'carrera'=>'Industrial',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 14',
                'email'=>'sepulbeda91@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9181162899',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],      
            [
                'NoControl'=>'15270901',
                'name'=>'Jackelyne',
                'a_paterno'=>'Rincon',
                'a_materno'=>'Herce',
                'carrera'=>'Mecanica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 15',
                'email'=>'jackelynerinconherce18@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'4421344438',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],      
            [
                'NoControl'=>'16270784',
                'name'=>'Rodolfo de Jesus',
                'a_paterno'=>'Hernandez',
                'a_materno'=>'Dominguez',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 16',
                'email'=>'rodolfodejesushernandezdomingu@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9612024719',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],      
            [
                'NoControl'=>'16270805',
                'name'=>'Cristian Alexis',
                'a_paterno'=>'Montoya',
                'a_materno'=>'Arguello',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 17',
                'email'=>'alexis.montoya97@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611847744',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],  
            [
                'NoControl'=>'16270588',
                'name'=>'Betsabe Raquel ',
                'a_paterno'=>'Lopez ',
                'a_materno'=>'Velazquez',
                'carrera'=>'Industrial',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 18',
                'email'=>'betsaberaquel@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611650015',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'16270860',
                'name'=>'Luis Roberto',
                'a_paterno'=>'Flores',
                'a_materno'=>'Juarez',
                'carrera'=>'Quimica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 19',
                'email'=>'floresjez.luis@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611292874',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'16270817',
                'name'=>'Fernando Alexis',
                'a_paterno'=>'Perez',
                'a_materno'=>'Lopez',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 20',
                'email'=>'darkeztblue4@outlook.es',
                'email_verified_at'=>null,
                'telefono'=>'9611651140',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'15270594',
                'name'=>'Eduardo Antonio',
                'a_paterno'=>'Vila',
                'a_materno'=>'Gordillo ',
                'carrera'=>'Electrica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 21',
                'email'=>'Lalito_vila@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9612509289',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'19270260',
                'name'=>'Andrea',
                'a_paterno'=>'Palacios',
                'a_materno'=>'Suarez',
                'carrera'=>'Gestion Empresarial',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 22',
                'email'=>'apalaciosuar@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611660360',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'19270928',
                'name'=>'Gabriela',
                'a_paterno'=>'Balbuena',
                'a_materno'=>'Cruz',
                'carrera'=>'Logistica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 23',
                'email'=>'carly201043@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611036997',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'16270697',
                'name'=>'Ramon Armando',
                'a_paterno'=>'Najera',
                'a_materno'=>'Courtois',
                'carrera'=>'Mecanica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 24',
                'email'=>'L16270697@tuxtla.tecnm.mx',
                'email_verified_at'=>null,
                'telefono'=>'9671298741',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'18270288',
                'name'=>'Guadalupe',
                'a_paterno'=>'Herrera',
                'a_materno'=>'Alegría',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 25',
                'email'=>'herreraalegrialupita@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9612305634',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'16270871',
                'name'=>'Oscar Aresno',
                'a_paterno'=>'Lopez',
                'a_materno'=>'Aguilar',
                'carrera'=>'Quimica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 26',
                'email'=>'L16270871@tuxtla.tecnm.mx',
                'email_verified_at'=>null,
                'telefono'=>'9671359621',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'M11270077',
                'name'=>'Cristian Alexander',
                'a_paterno'=>'Ruiz',
                'a_materno'=>'Pérez',
                'carrera'=>'Electrica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 27',
                'email'=>'cristianruiz@gudtech.tech',
                'email_verified_at'=>null,
                'telefono'=>'9321468941',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'15270948',
                'name'=>'Erika',
                'a_paterno'=>'Díaz',
                'a_materno'=>'Antonio',
                'carrera'=>'Gestion Empresarial',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 28',
                'email'=>'luciadiaz141296@hotmail.com ',
                'email_verified_at'=>null,
                'telefono'=>'9612554702',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],[
                'NoControl'=>'C16270816',
                'name'=>'Marco Antonio',
                'a_paterno'=>'Pérez',
                'a_materno'=>'Gómez',
                'carrera'=>'Quimica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 29',
                'email'=>'LC16270816@tuxtla.tecnm.mx',
                'email_verified_at'=>null,
                'telefono'=>'9612063213',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'17271140',
                'name'=>'Andres',
                'a_paterno'=>'Núñez',
                'a_materno'=>'Martìnez',
                'carrera'=>'Industrial',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 30',
                'email'=>'andres.nmtz@outlook.com',
                'email_verified_at'=>null,
                'telefono'=>'9612351517',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],   
            [
                'NoControl'=>'16270800',
                'name'=>'Bryant Edward',
                'a_paterno'=>'Méndez',
                'a_materno'=>'Gómez',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 31',
                'email'=>'edwardmndzgomz@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611575591',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'17271205',
                'name'=>'Ithalya Karina',
                'a_paterno'=>'Gordillo',
                'a_materno'=>'López',
                'carrera'=>'Industrial',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 32',
                'email'=>'ithalyagordillo@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9613064140',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'19270998',
                'name'=>'Adrián',
                'a_paterno'=>'Díaz',
                'a_materno'=>'Hernández',
                'carrera'=>'Logistica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 33',
                'email'=>'ad602778@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9612156585',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'16270806',
                'name'=>'Victor',
                'a_paterno'=>'Monzon',
                'a_materno'=>'Monterrubio',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 34',
                'email'=>'vicmonzon5@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9613699550',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'19270727',
                'name'=>'Luis Guadalupe',
                'a_paterno'=>'Santana',
                'a_materno'=>'Calvo ',
                'carrera'=>'Mecanica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 35',
                'email'=>'Chackbalamsito@live.com.mx',
                'email_verified_at'=>null,
                'telefono'=>'9611930501',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'16270794',
                'name'=>'Jorge David',
                'a_paterno'=>'Martínez',
                'a_materno'=>'Pérez',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 36',
                'email'=>'jorgemartinezdp98@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9612435270',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'19270878',
                'name'=>'Anahí',
                'a_paterno'=>'Sibaja',
                'a_materno'=>'Trejo',
                'carrera'=>'Industrial',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 37',
                'email'=>'anahisibtre07@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611723654',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'14270747',
                'name'=>'Jonathan Eduardo',
                'a_paterno'=>'Aquino',
                'a_materno'=>'Mandujano',
                'carrera'=>'Mecanica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 38',
                'email'=>'jeam_96@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611544100',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'C16270753',
                'name'=>'Edson Jair',
                'a_paterno'=>'Cruz',
                'a_materno'=>'Cruz',
                'carrera'=>'Electronica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 39',
                'email'=>'edsoncruz829@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611994547',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'16270895',
                'name'=>'Dennis Aurora',
                'a_paterno'=>'Sesma',
                'a_materno'=>'Hernández',
                'carrera'=>'Quimica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 40',
                'email'=>'srita.dennis@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9612081289',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'17271050',
                'name'=>'Jeziel',
                'a_paterno'=>'Penagos',
                'a_materno'=>'Suárez',
                'carrera'=>'Mecanica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 41',
                'email'=>'jezpesu@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9613649868',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ], 
            [
                'NoControl'=>'16270840',
                'name'=>'Luis Enrique',
                'a_paterno'=>'Velazquez',
                'a_materno'=>'Perez',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 42',
                'email'=>'kiritosocial18@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9666658857',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],   
            [
                'NoControl'=>'C16270784',
                'name'=>'Yuriana Janeth',
                'a_paterno'=>'González',
                'a_materno'=>'Lorenzana',
                'carrera'=>'Logistica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 43',
                'email'=>'yurianagonzalezl1997@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9613287979',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'16270835',
                'name'=>'Darwin Alfredo',
                'a_paterno'=>'Trujillo',
                'a_materno'=>'Hernández',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 44',
                'email'=>'darwin.th@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9614557472',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'17270153',
                'name'=>'José Elias',
                'a_paterno'=>'Espinosa',
                'a_materno'=>'Ramírez',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 45',
                'email'=>'elias144445@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9616605597',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'M12270664',
                'name'=>'Antonio de Jesus',
                'a_paterno'=>'Sánchez',
                'a_materno'=>'Vargas',
                'carrera'=>'Electrica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 46',
                'email'=>'ha-toni@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611770366',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'18270146 ',
                'name'=>'Andres',
                'a_paterno'=>'Luis',
                'a_materno'=>'Ibáñez',
                'carrera'=>'Bioquimica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 47',
                'email'=>'andres.ibnz23@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9612736738',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'16270420',
                'name'=>'Osvaldo',
                'a_paterno'=>'Escobar',
                'a_materno'=>'Solis',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto 48',
                'email'=>'aldo2sol2@gmail.com ',
                'email_verified_at'=>null,
                'telefono'=>'9614298472',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'16270819',
                'name'=>'Diego de Jesús',
                'a_paterno'=>'Peñate',
                'a_materno'=>'Ramírez',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 49',
                'email'=>'dpenate32@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9616937861',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'14270566',
                'name'=>'Luis Fernando',
                'a_paterno'=>'Díaz',
                'a_materno'=>'De la Cruz',
                'carrera'=>'Electronica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 50',
                'email'=>'spiritofvengeance96@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611809714',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'17270458',
                'name'=>'Montserrat',
                'a_paterno'=>'Alegría ',
                'a_materno'=>'Rangel ',
                'carrera'=>'Bioquimica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 51',
                'email'=>'montse.alegria@outlook.es',
                'email_verified_at'=>null,
                'telefono'=>'9613641691',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],
            [
                'NoControl'=>'18270639',
                'name'=>'Jorge Elías',
                'a_paterno'=>'Pinto',
                'a_materno'=>'Cancino',
                'carrera'=>'Industrial',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'2',
                'tema'=>'proyecto 52',
                'email'=>'eliaspinto78@gmail.com ',
                'email_verified_at'=>null,
                'telefono'=>'9631475994',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],    
            [
                'NoControl'=>'15270242',
                'name'=>'Saintus',
                'a_paterno'=>'Zephir',
                'a_materno'=>'Zephir',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto ',
                'email'=>'zsaintus92@yahoo.com ',
                'email_verified_at'=>null,
                'telefono'=>'7621153580',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],     
            [
                'NoControl'=>'15271099',
                'name'=>'Evelyn Lizeth',
                'a_paterno'=>'González',
                'a_materno'=>'Barragán',
                'carrera'=>'Gestion Empresarial',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto ',
                'email'=>'Evelyn_glez97@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611163545',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ], 
            [
                'NoControl'=>'21270315',
                'name'=>'José Jonathan',
                'a_paterno'=>'Nañez',
                'a_materno'=>'Reyes',
                'carrera'=>'Electronica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto ',
                'email'=>'josejonathannanezreyes@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9612000116',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ], 
            [
                'NoControl'=>'15270720',
                'name'=>'Mario Alberto',
                'a_paterno'=>'Cortez',
                'a_materno'=>'Verde',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto ',
                'email'=>'mario_cv7@outlook.com',
                'email_verified_at'=>null,
                'telefono'=>'9612776642',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ], 
            [
                'NoControl'=>'16270416',
                'name'=>'Citlali Guadalupe',
                'a_paterno'=>'Reyes',
                'a_materno'=>'Jiménez',
                'carrera'=>'Electrica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto ',
                'email'=>'jnlupita.77@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611517476',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ], 
            [
                'NoControl'=>'17270349',
                'name'=>'Aurora del Carmen ',
                'a_paterno'=>'Moreno',
                'a_materno'=>'Sarmiento',
                'carrera'=>'Gestion Empresarial',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto ',
                'email'=>'aurora-sarmiento@outlook.es ',
                'email_verified_at'=>null,
                'telefono'=>'9611709505',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ], 
            [
                'NoControl'=>'14271041',
                'name'=>'Carlos Alberto',
                'a_paterno'=>'Hidalgo',
                'a_materno'=>'Ruiz',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto ',
                'email'=>'bet0_93@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9671309999',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ], 
            [
                'NoControl'=>'16270820',
                'name'=>'Maribel',
                'a_paterno'=>'Rascón',
                'a_materno'=>'Chaires',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto ',
                'email'=>'crazyfriend510@hotmail.com',
                'email_verified_at'=>null,
                'telefono'=>'5560614785',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ], 
            [
                'NoControl'=>'16270844',
                'name'=>'Jorge Alberto',
                'a_paterno'=>'Zebadua',
                'a_materno'=>'Cruz',
                'carrera'=>'Sistemas Computacionales',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto ',
                'email'=>'jorgezebadua98@gmail.com',
                'email_verified_at'=>null,
                'telefono'=>'9611702885',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],     
            [
                'NoControl'=>'18270731 ',
                'name'=>'Nydia',
                'a_paterno'=>'Ocaña',
                'a_materno'=>'Cruz',
                'carrera'=>'Logistica',
                'campus'=>'Instituto Tecnologico de Tuxtla Gutierrez',
                'planDeestudios'=>'1',
                'tema'=>'proyecto ',
                'email'=>'nydia280800@gmail.com ',
                'email_verified_at'=>null,
                'telefono'=>'9612326405',
                'rol' => 'egresado',
                'estado'=> 'Tramite_Iniciado',
                'password'=> bcrypt('prueba123'),
            ],              
        ]);
    }
}
